### ISSUE TITLE
Provide a default sample setup deployment against a local machine

### ISSUE THREAD

**Issue by kasunbg** [wso2-incubator/testgrid#117]
**description**

TestGrid should be intuitive enough for the users to understand. To improve the first-time user experience, we need to support:

1. local machine / h2 db / JDK8 as the infrastructure
2. single node deployment
3. All scenarios

**Comment by kasunbg** [comment]
@yasassri shall we provide above as well as part of https://github.com/wso2-incubator/testgrid/issues/282?

**Comment by yasassri** [comment]
We can execute shell scripts in the following manner. 

```
# TestGrid Test Configuration Parameters
productName: "IS"
productVersion: "5.4.0"
channel: "LTS"
deploymentPatterns:
    -  "pattern-2"
infraParams:
  - osName: "Ubuntu"
    osVersion:
      - "16.04"
    databaseName: "MYSQL"
    databaseVersion:
      - "5.7"
    jdk:
        - "ORACLE_JDK8"
scenarios:
    -  "solution01"
infrastructure:
  providerType: "AWS"
  clusterType: "None"
  instanceType: "EC2"
  name: "pattern-2"
  securityProperties:
    apiKey: "242424"
    sshKey: "abc.key"
  scripts:
    - scriptType: "INFRA_CREATE"
      filePath: "infra-provision.sh"
      name: "provision"
      environmentScriptParameters:
      scriptParameters:
    - scriptType: "INFRA_DESTROY"
      filePath: "infra-destroy.sh"
      name: "destroy"
      environmentScriptParameters:
      scriptParameters:
```
