### ISSUE TITLE
Re-Design the configuration file required for each testplan

### ISSUE THREAD

**Issue by kasunbg** [wso2-incubator/testgrid#287]
**Description:**
$subject. A sample of the initial draft config we came up with can be found here. [1]

But, product teams does not know about channels. And, operating system and jdk should not be configured by the product teams. 

Hence, we should come up with a base test plan (testgrid-base-testplan-config-1.0.0.yaml). That is configured and maintained by TestGrid folks. This will contain all the major infrastructure our products will support. Product teams will write configuration file based on testgrid-base-testplan-config-1.0.0.yaml. In there, they can include/exclude any infrastructure as necessary.

[1] initial draft: https://gist.github.com/kasunbg/48b2ee7e9dbfda95a6e710acff9493d7

**Comment by kasunbg** [comment]
The new design will retrieve the infrastructure-value-set from an API. Current plan is to store this information in a google sheet that is both human and machine readable. 

This is now reflected in the test-plan execution sequence:

![image](https://user-images.githubusercontent.com/936037/35108874-b501b90a-fc9a-11e7-93d3-09544cc0ca6b.png)

**Comment by kasunbg** [comment]
And, the job creation flow is as follows. 


![image](https://user-images.githubusercontent.com/936037/35110024-de417c3a-fc9d-11e7-830c-ce5cb4dd57ee.png)


To create a job, the user need to send following information along with the request:

```
test-plan-name: <testPlan name>
test-plan-type: <type-durable/ephemeral>
infrastructure:
  repository: <infra-repository URL>
  inputs:
  - <commandline-parameter1>
  - <commandline-parameter2>
  - <commandline-parameter3>
deployment:
  repository: <deployment-repository URL>
  inputs:
  - <commandline-parameter1>
  - <commandline-parameter2>
  - <commandline-parameter3>
scenarios:
  repository: <scenarios-repository URL>
  inputs:
  - <commandline-parameter1>
  - <commandline-parameter2>
  - <commandline-parameter3>
```
The jobs with type 'ephemeral' are not shown in the dashboard and has a shorter lifespan. The status of this type jobs can only be consumed via the TestPlan API. 

The 'durable' jobs has a longer lifespan, and is shown in the dashboard. Thru the dashboard, viewers can find out the following:

1. Current status of the job
2. Historical data and build success/failure trends of the job
